/* eslint-disable */
// Generated from packages/shared/openapi/han-note.openapi.json by scripts/generate-shared-client.mjs.
// Do not edit this file directly.

export type AnalyzeRequest = {
  text: string;
};

export type AnalyzeResponse = {
  analysis_id: string;
  original_text: string;
  sentences: Array<SentenceAnalysisResponse>;
};

export type AuthSessionResponse = {
  user: AuthUserResponse;
  access_token: string;
  refresh_token: string;
  access_token_expires_at: string;
  refresh_token_expires_at: string;
};

export type AuthUserResponse = {
  id: string;
  email: string;
  display_name: string;
  timezone: string;
  created_at: string;
};

export type ExplainSentenceRequest = {
  sentence_index: number;
  text: string;
  translation_vi: string;
  natural_explanation_vi?: string | null;
  tokens: Array<ExplainTokenRequestItem>;
};

export type ExplainTokenRequestItem = {
  token_index: number;
  text: string;
  pinyin: string | null;
  meaning_vi_brief?: string | null;
  user_status: string;
};

export type ExplainTokensRequest = {
  original_text: string;
  sentences: Array<ExplainSentenceRequest>;
};

export type ExplainTokensResponse = {
  explanations: Array<ExplanationResponseItem>;
};

export type ExplanationExample = {
  zh: string;
  pinyin: string | null;
  vi: string;
};

export type ExplanationResponseItem = {
  word: string;
  pinyin: string;
  meaning_vi: string;
  meaning_in_context_vi: string;
  part_of_speech: string;
  usage_note_vi: string;
  examples: Array<ExplanationExample>;
  difficulty_suggestion: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type LogoutRequest = {
  refresh_token?: string | null;
};

export type NotificationSettingsResponse = {
  timezone: string;
  daily_reminder_time: string;
  app_push_enabled: boolean;
  telegram_enabled: boolean;
  telegram_chat_id: string | null;
  mobile_push_token: string | null;
  privacy_no_source_sentence: boolean;
  privacy_anonymize_before_save: boolean;
};

export type NotificationSettingsUpdateRequest = {
  timezone: string;
  daily_reminder_time: string;
  app_push_enabled: boolean;
  telegram_enabled: boolean;
  telegram_chat_id?: string | null;
  mobile_push_token?: string | null;
  privacy_no_source_sentence: boolean;
  privacy_anonymize_before_save: boolean;
};

export type PushTokenRegisterRequest = {
  push_token: string;
};

export type RefreshRequest = {
  refresh_token: string;
};

export type RegisterRequest = {
  email: string;
  password: string;
  display_name: string;
  timezone?: string | null;
};

export type ReviewSessionCompleteRequest = {
  results: Array<string>;
};

export type ReviewSessionCompleteResponse = {
  total: number;
  forgot: number;
  vague: number;
  remembered: number;
  easy: number;
};

export type ReviewSubmitRequest = {
  result: string;
};

export type ReviewSubmitResponse = {
  vocab_id: string;
  result: string;
  previous_stage: number;
  next_stage: number;
  next_review_at: string;
  next_review_label: string;
  status: string;
};

export type ReviewTodayItem = {
  id: string;
  word: string;
  pinyin: string;
  meaning_vi: string;
  example_zh: string | null;
  example_vi: string | null;
  difficulty: string;
  review_stage: number;
};

export type ReviewTodayResponse = {
  date: string;
  timezone: string;
  due_count: number;
  hard_count: number;
  estimated_minutes: number;
  items: Array<ReviewTodayItem>;
};

export type SentenceAnalysisResponse = {
  sentence_index: number;
  text: string;
  translation_vi: string;
  natural_explanation_vi: string;
  tokens: Array<TokenResponse>;
};

export type TelegramTestRequest = {
  chat_id?: string | null;
};

export type TokenResponse = {
  token_index: number;
  text: string;
  pinyin: string | null;
  meaning_vi_brief: string | null;
  token_type: string;
  is_learnable: boolean;
  status: string;
  confidence?: number | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, never>;
};

export type VocabularyCreateItem = {
  word: string;
  pinyin: string;
  meaning_vi: string;
  meaning_in_context_vi: string;
  part_of_speech: string;
  usage_note_vi?: string | null;
  difficulty?: string;
  source_sentence_zh?: string | null;
  source_sentence_vi?: string | null;
  examples?: Array<ExplanationExample>;
};

export type VocabularyCreateRequest = {
  items: Array<VocabularyCreateItem>;
};

export type VocabularyDetailItem = {
  id: string;
  word: string;
  pinyin: string;
  meaning_vi: string;
  meaning_in_context_vi: string;
  part_of_speech: string;
  usage_note_vi: string | null;
  status: string;
  difficulty: string;
  review_stage: number;
  review_count: number;
  next_review_at: string | null;
  next_review_label: string;
  example_zh: string | null;
  example_vi: string | null;
  successful_review_count: number;
  memory_strength: number;
  examples: Array<VocabularyExampleCreateRequest>;
};

export type VocabularyExampleCreateRequest = {
  source_sentence_zh?: string | null;
  source_sentence_vi?: string | null;
  example_zh: string;
  example_pinyin?: string | null;
  example_vi: string;
  is_user_source?: boolean;
};

export type VocabularyListItem = {
  id: string;
  word: string;
  pinyin: string;
  meaning_vi: string;
  meaning_in_context_vi: string;
  part_of_speech: string;
  usage_note_vi: string | null;
  status: string;
  difficulty: string;
  review_stage: number;
  review_count: number;
  next_review_at: string | null;
  next_review_label: string;
  example_zh: string | null;
  example_vi: string | null;
};

export type VocabularyUpdateRequest = {
  status?: string | null;
  difficulty?: string | null;
  next_review_at?: string | null;
};

export type Token = TokenResponse;
export type TokenStatus = TokenResponse["status"];
export type SentenceAnalysis = SentenceAnalysisResponse;
export type Explanation = ExplanationResponseItem;
export type AuthUser = AuthUserResponse;
export type AuthSession = AuthSessionResponse;
export type VocabularyItem = VocabularyListItem;
export type VocabularyDetail = VocabularyDetailItem;
export type NotificationSettings = NotificationSettingsResponse;
export type ReviewResult = ReviewSubmitRequest["result"];
export type HealthzResponse = {
  [key: string]: string;
};
export type ReviewSessionSummary = ReviewSessionCompleteResponse;
export type TelegramTestResponse = {
  [key: string]: string;
};
export type PushTokenRegisterResponse = {
  [key: string]: string;
};

export type ApiClient = ReturnType<typeof createApiClient>;

export type ApiClientOptions = {
  getAccessToken?: () => string | null | Promise<string | null>;
};

async function request<T>(
  input: RequestInfo | URL,
  authConfig: ApiClientOptions = {},
  init?: RequestInit
): Promise<T> {
  const accessToken = authConfig.getAccessToken ? await authConfig.getAccessToken() : null;
  const response = await fetch(input, {
    headers: {
      "Content-Type": "application/json",
      ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}),
      ...(init?.headers ?? {})
    },
    ...init
  });

  if (!response.ok) {
    const text = await response.text();
    if (text) {
      try {
        const parsed = JSON.parse(text) as { detail?: unknown; message?: unknown };
        if (typeof parsed.detail === "string") {
          throw new Error(parsed.detail);
        }
        if (typeof parsed.message === "string") {
          throw new Error(parsed.message);
        }
      } catch (error) {
        if (error instanceof SyntaxError) {
          // Ignore non-JSON error bodies and fall through to the raw text message.
        } else if (error instanceof Error) {
          throw error;
        }
      }
    }
    throw new Error(text || `Request failed with status ${response.status}`);
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return response.json() as Promise<T>;
}

export function createApiClient(baseUrl: string, options: ApiClientOptions = {}) {
  const root = baseUrl.replace(/\/$/, "");
  const authConfig = options;

  return {
    healthz() {
      return request<HealthzResponse>(`${root}/healthz`, authConfig);
    },

    register(payload: RegisterRequest) {
      return request<AuthSessionResponse>(`${root}/api/auth/register`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    login(payload: LoginRequest) {
      return request<AuthSessionResponse>(`${root}/api/auth/login`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    refresh(payload: RefreshRequest) {
      return request<AuthSessionResponse>(`${root}/api/auth/refresh`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    logout(payload?: LogoutRequest | null) {
      return request<Record<string, string>>(`${root}/api/auth/logout`, authConfig, {
        method: "POST",
        body: payload ? JSON.stringify(payload) : undefined
      });
    },

    me() {
      return request<AuthUserResponse>(`${root}/api/auth/me`, authConfig);
    },

    analyze(input: string | AnalyzeRequest) {
      const payload: AnalyzeRequest = typeof input === "string" ? { text: input } : input;
      return request<AnalyzeResponse>(`${root}/api/analyze`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    explainTokens(payload: ExplainTokensRequest) {
      return request<ExplainTokensResponse>(`${root}/api/explain-tokens`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    saveVocabulary(payload: VocabularyCreateRequest) {
      return request<Array<VocabularyListItem>>(`${root}/api/vocabulary`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    listVocabulary(query?: string, status?: string) {
      const url = new URL(`${root}/api/vocabulary`);
      if (query) url.searchParams.set("query", query);
      if (status) url.searchParams.set("status", status);
      return request<Array<VocabularyListItem>>(url, authConfig);
    },

    getVocabulary(id: string) {
      return request<VocabularyDetailItem>(`${root}/api/vocabulary/${id}`, authConfig);
    },

    updateVocabulary(id: string, payload: VocabularyUpdateRequest) {
      return request<VocabularyDetailItem>(`${root}/api/vocabulary/${id}`, authConfig, {
        method: "PATCH",
        body: JSON.stringify(payload)
      });
    },

    addVocabularyExample(id: string, payload: VocabularyExampleCreateRequest) {
      return request<VocabularyDetailItem>(`${root}/api/vocabulary/${id}/examples`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    reviewsToday() {
      return request<ReviewTodayResponse>(`${root}/api/reviews/today`, authConfig);
    },

    startReviewSession() {
      return request<ReviewTodayResponse>(`${root}/api/reviews/session/start`, authConfig, {
        method: "POST"
      });
    },

    submitReview(id: string, result: ReviewResult | ReviewSubmitRequest) {
      const payload: ReviewSubmitRequest =
        typeof result === "string" ? { result } : result;
      return request<ReviewSubmitResponse>(`${root}/api/reviews/${id}/submit`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    completeReview(results: ReviewResult[] | ReviewSessionCompleteRequest) {
      const payload: ReviewSessionCompleteRequest = Array.isArray(results)
        ? { results }
        : results;
      return request<ReviewSessionSummary>(`${root}/api/reviews/session/complete`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    getNotificationSettings() {
      return request<NotificationSettingsResponse>(`${root}/api/notification-settings`, authConfig);
    },

    updateNotificationSettings(
      payload: NotificationSettingsUpdateRequest | NotificationSettings
    ) {
      return request<NotificationSettingsResponse>(`${root}/api/notification-settings`, authConfig, {
        method: "PUT",
        body: JSON.stringify(payload)
      });
    },

    testTelegram(chatId?: string | null | TelegramTestRequest) {
      const payload: TelegramTestRequest =
        typeof chatId === "object" && chatId !== null ? chatId : { chat_id: chatId ?? null };
      return request<TelegramTestResponse>(`${root}/api/notifications/test-telegram`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    },

    registerPushToken(pushToken: string | PushTokenRegisterRequest) {
      const payload: PushTokenRegisterRequest =
        typeof pushToken === "string" ? { push_token: pushToken } : pushToken;
      return request<PushTokenRegisterResponse>(`${root}/api/notifications/register-push-token`, authConfig, {
        method: "POST",
        body: JSON.stringify(payload)
      });
    }
  };
}
